name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Lint
        run: |
          flake8 src tests

  deploy:
    name: Deploy Model
    runs-on: ubuntu-latest
    needs: [lint]  # Ensure lint job is complete before deploy
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Model Training
        run: |
          python src/train.py

      - name: Save Model Artifact
        uses: actions/upload-artifact@v4
        with:
          name: trained-model
          path: model.pkl

  test:
    name: Test Code
    runs-on: ubuntu-latest
    needs: [deploy]  # Ensure deploy job is complete before running tests
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Download Model Artifact
        uses: actions/download-artifact@v4
        with:
          name: trained-model
        
      - name: Run Tests
        run: |
          pytest tests
